TugasEAITika/Controllers/KelasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using TugasEAITika.Models;

namespace TugasEAITika.Controllers
{
    public class KelasController : Controller
    {
        private readonly ILogger<RestController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string _connstring;

        public KelasController(ILogger<RestController> logger, IConfiguration Configuration)
        {
            _logger = logger;
            _configuration = Configuration;
            _connstring = _configuration.GetConnectionString("DefaultDatabase");
        }
        // GET: KelasController
        public ActionResult Index()
        {
            return View();
        }

        // GET: KelasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: KelasController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KelasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: KelasController/Edit/5
        public ActionResult Edit(int id)
        {
            List<Kelas> res = new List<Kelas>();
            SqlConnection conSQL = new SqlConnection(_connstring);
            try
            {
                conSQL.Open();
                string sql = @"select * from reservasi_kelas rk where id = @id;";
                SqlCommand command = new SqlCommand(sql, conSQL);
                command.Parameters.Add(new SqlParameter("@id", id));
                SqlDataReader dtr = command.ExecuteReader();
                var datatable = new DataTable();
                datatable.Load(dtr);
                if (datatable.Rows.Count > 0)
                {
                    var serializedMyObjects = JsonConvert.SerializeObject(datatable);
                    res = (List<Kelas>)JsonConvert.DeserializeObject(serializedMyObjects, typeof(List<Kelas>));
                    DateTime tanggal = DateTime.Parse(res[0].tanggal_peminjaman);
                    res[0].tanggal_peminjaman = tanggal.ToString("yyy-MM-dd");
                }
            }
            catch
            {

            }
            finally
            {
                conSQL.Close();
            }
            return View(res[0]);
        }

        // POST: KelasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: KelasController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: KelasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TugasEAITika/Controllers/PraktikumController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TugasEAITika.Controllers
{
    public class PraktikumController : Controller
    {
        // GET: PraktikumController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PraktikumController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PraktikumController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PraktikumController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PraktikumController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PraktikumController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PraktikumController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PraktikumController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TugasEAITika/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TugasEAITika</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Peminjaman Ruangan</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div id="wrapper">
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-people-carry"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Peminjaman Ruangan <sup></sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" asp-controller="Home" asp-action="Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->
        <div class="sidebar-heading">Peminjaman</div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link" asp-controller="Kelas" asp-action="Create">
            <i class="fas fa-fw fa-cog"></i>
            <span>Ruang Kelas</span>
          </a>
        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link" asp-controller="Praktikum" asp-action="Create">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Ruang Praktikum</span>
          </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <!-- <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div> -->

        <!-- Sidebar Message -->
        <!-- <div class="sidebar-card d-none d-lg-flex">
          <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="..." />
          <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
          <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
        </div> -->
      </ul>
      <div class="container-fluid mt-5">
          
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        
      </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  <script type="text/javascript"  src="~/js/jquery.soap.js"></script>
  <script type="text/javascript" >
    function TestSoap() {
      console.log("test");
      
      $.soap({
        url: '/Service.asmx',
        data: {},
        method: 'TestMachine',
        appendMethodToURL: false,
        beforeSend: function (SOAPEnvelope) {
          console.log("before" + SOAPEnvelope.toString());
        },
        success: function (soapResponse) {
          console.log("success")
          // do stuff with soapResponse
          // if you want to have the response as JSON use soapResponse.toJSON();
          // or soapResponse.toString() to get XML string
          // or soapResponse.toXML() to get XML DOM
        },
        error: function (SOAPResponse) {
          // show error
          console.log("error")
        }
      });
    }
  </script>
    
</body>
</html>